name: yasone
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.10.0=py312hca03da5_0
  - aom=3.12.1=ha237518_0
  - appnope=0.1.4=py312hca03da5_0
  - argon2-cffi=25.1.0=py312hca03da5_0
  - argon2-cffi-bindings=25.1.0=py312h254cc4a_0
  - arrow-cpp=21.0.0=hc027f7d_2
  - astroalign=2.6.2=pyhd8ed1ab_0
  - astropy=7.1.1=py312h03d0aa3_0
  - astropy-base=7.2.0=py312ha11c99a_0
  - astropy-healpix=1.1.2=py312ha11c99a_1
  - astropy-iers-data=0.2025.12.8.0.38.44=py312hca03da5_0
  - astroscrappy=1.2.0=py312h4409184_2
  - asttokens=3.0.0=py312hca03da5_0
  - async-lru=2.0.5=py312hca03da5_0
  - attrs=25.4.0=py312hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hd40f934_1
  - aws-c-http=0.10.4=he148155_1
  - aws-c-io=0.21.4=h89d1e94_1
  - aws-c-mqtt=0.13.3=h8d8bef9_4
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - babel=2.17.0=py312hca03da5_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhcf101f3_2
  - beautifulsoup4=4.14.2=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=6.3.0=py312hca03da5_0
  - blosc=1.21.6=h5499902_0
  - bokeh=3.8.1=pyhd8ed1ab_0
  - bottleneck=1.4.2=py312h03d0aa3_1
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotlicffi=1.2.0.0=py312h50f4ffc_0
  - brunsli=0.1=he0dfb12_2
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.22.0=h7d537c7_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - ccdproc=2.5.1=pyhd8ed1ab_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312h73c2a22_1
  - cfitsio=4.6.2=h7200ff5_1
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.4=py312hca03da5_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - comm=0.2.3=py312hca03da5_0
  - contourpy=1.3.3=py312h20e30b6_0
  - cycler=0.12.1=py312hca03da5_0
  - cytoolz=1.1.0=py312h4409184_1
  - dask=2025.12.0=pyhcf101f3_0
  - dask-core=2025.12.0=pyhcf101f3_1
  - dask-image=2025.11.0=pyhd8ed1ab_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py312h50f4ffc_1
  - decorator=5.2.1=py312hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distributed=2025.12.0=pyhcf101f3_1
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - executing=2.2.1=py312hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - fitsio=1.3.0=np2py312h2944666_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.61.0=py312haa24f5a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - geos=3.14.1=h5afe852_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.5.0=h5c6a83d_0
  - google-crc32c=1.8.0=py312h2476293_0
  - graphite2=1.3.14=hc377ac9_1
  - h11=0.16.0=py312hca03da5_1
  - harfbuzz=10.2.0=he637ebf_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py312hca03da5_0
  - httpx=0.28.1=py312hca03da5_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py312hca03da5_0
  - imagecodecs=2025.11.11=py312he3dd903_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.31.0=py312h7eb115d_0
  - ipython=9.7.0=py312hca03da5_0
  - ipython_pygments_lexers=1.1.1=py312hca03da5_0
  - ipywidgets=8.1.7=py312hca03da5_0
  - jaraco.classes=3.4.0=pyhcf101f3_3
  - jaraco.context=6.0.2=pyhcf101f3_1
  - jaraco.functools=4.4.0=pyhcf101f3_1
  - jedi=0.19.2=py312hca03da5_0
  - jinja2=3.1.6=py312hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.12.1=py312hca03da5_0
  - jsonschema=4.25.0=py312hca03da5_1
  - jsonschema-specifications=2025.9.1=py312hca03da5_0
  - jupyter=1.1.1=py312hca03da5_0
  - jupyter-lsp=2.2.5=py312hca03da5_0
  - jupyter_client=8.6.3=py312hca03da5_1
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.9.1=py312hca03da5_0
  - jupyter_events=0.12.0=py312hca03da5_1
  - jupyter_server=2.17.0=py312hca03da5_0
  - jupyter_server_terminals=0.5.3=py312hca03da5_0
  - jupyterlab=4.5.0=py312hca03da5_0
  - jupyterlab_pygments=0.3.0=py312hca03da5_0
  - jupyterlab_server=2.28.0=py312hca03da5_0
  - jupyterlab_widgets=3.0.15=py312hca03da5_0
  - jxrlib=1.2=h2c76fc5_0
  - keyring=25.7.0=pyh534df25_0
  - kiwisolver=1.4.9=py312haeee614_0
  - krb5=1.21.3=h237132a_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250814.1=cxx17_ha86d76d_0
  - libaec=1.1.4=h51d1e36_0
  - libavif=1.3.0=h839b4eb_0
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libgrpc=1.74.1=h941cc20_0
  - libiconv=1.16=h80987f9_3
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=6.33.0=hab92411_0
  - libre2-11=2025.11.05=hd4f4e8d_0
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h367c460_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=20.1.8=he822017_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py312h11d1bbd_1
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py312h80987f9_0
  - matplotlib=3.10.7=py312hca03da5_0
  - matplotlib-base=3.10.7=py312haa222d5_0
  - matplotlib-inline=0.2.1=py312hca03da5_0
  - mistune=3.1.2=py312hca03da5_0
  - more-itertools=10.8.0=pyhcf101f3_1
  - msgpack-python=1.1.2=py312h84eede6_1
  - narwhals=2.14.0=pyhcf101f3_0
  - nbclient=0.10.2=py312hca03da5_0
  - nbconvert=7.16.6=py312hca03da5_0
  - nbconvert-core=7.16.6=py312hca03da5_0
  - nbconvert-pandoc=7.16.6=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - networkx=3.6.1=pyhcf101f3_0
  - notebook=7.5.0=py312hca03da5_0
  - notebook-shim=0.2.4=py312hca03da5_0
  - numcodecs=0.16.5=py312h5978115_0
  - numexpr=2.14.1=py312h5fbe615_0
  - numpy=2.3.5=py312h4bb6f22_0
  - numpy-base=2.3.5=py312h23175f9_0
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.0=hd6530ca_1
  - packaging=25.0=py312hca03da5_1
  - pandas=2.3.3=py312h3f644e9_1
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py312hca03da5_0
  - parso=0.8.5=py312hca03da5_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py312hca03da5_1
  - pillow=12.0.0=py312he2d6fe4_1
  - pims=0.7=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py312hca03da5_0
  - prometheus_client=0.21.1=py312hca03da5_0
  - prompt-toolkit=3.0.52=py312hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py312hca03da5_0
  - pyarrow=21.0.0=py312h3f644e9_1
  - pyavm=0.9.8=pyhc455866_0
  - pycparser=2.23=py312hca03da5_0
  - pyerfa=2.0.1.5=py312hbe26d11_1
  - pygments=2.19.2=py312hca03da5_0
  - pyparsing=3.2.5=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_1
  - python=3.12.8=h89a136b_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.21.2=py312hca03da5_0
  - python-json-logger=4.0.0=py312hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=py312hca03da5_0
  - pyvo=1.8=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h091b9d3_0
  - pyzmq=27.1.0=py312h5a8c52c_1
  - qtconsole=5.7.0=py312hca03da5_0
  - qtpy=2.4.3=py312hca03da5_0
  - re2=2025.11.05=h1413154_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py312hca03da5_0
  - reproject=0.19.0=py312ha11c99a_0
  - requests=2.32.5=py312hca03da5_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.28.0=py312h931abed_0
  - scikit-image=0.26.0=np2py312ha921b1d_0
  - scipy=1.16.3=py312h08a1045_0
  - seaborn=0.13.2=py312hca03da5_3
  - send2trash=1.8.2=py312hca03da5_1
  - sep=1.4.1=py312hc7121bb_3
  - setuptools=80.9.0=py312hca03da5_0
  - shapely=2.1.2=py312h35cd81b_2
  - six=1.17.0=py312hca03da5_0
  - slicerator=1.1.0=pyhd8ed1ab_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=py312hca03da5_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - stack_data=0.6.3=py312hca03da5_0
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=py312hca03da5_0
  - tifffile=2025.12.20=pyhd8ed1ab_0
  - tinycss2=1.4.0=py312hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli-w=1.2.0=pyhd8ed1ab_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py312haa24f5a_0
  - traitlets=5.14.3=py312hca03da5_0
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py312hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.13=py312hca03da5_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.45.1=py312hca03da5_0
  - widgetsnbextension=4.0.14=py312hca03da5_0
  - wrapt=1.17.3=py312h163523d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zarr=3.1.5=pyhcf101f3_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zfp=1.0.1=ha86207d_5
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.0.7=h1a8c8d9_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - arya-aeyobd==0.0.1
      - astrometry-net-client==0.6.0
      - astroquery==0.4.11
      - configobj==5.0.9
      - ipympl==0.9.8
      - jaraco-classes==3.4.0
      - lacosmic==1.3.0
      - loguru==0.7.3
      - pyobjc==12.1
      - pyobjc-core==12.1
      - pyobjc-framework-accessibility==12.1
      - pyobjc-framework-accounts==12.1
      - pyobjc-framework-addressbook==12.1
      - pyobjc-framework-adservices==12.1
      - pyobjc-framework-adsupport==12.1
      - pyobjc-framework-applescriptkit==12.1
      - pyobjc-framework-applescriptobjc==12.1
      - pyobjc-framework-applicationservices==12.1
      - pyobjc-framework-apptrackingtransparency==12.1
      - pyobjc-framework-arkit==12.1
      - pyobjc-framework-audiovideobridging==12.1
      - pyobjc-framework-authenticationservices==12.1
      - pyobjc-framework-automaticassessmentconfiguration==12.1
      - pyobjc-framework-automator==12.1
      - pyobjc-framework-avfoundation==12.1
      - pyobjc-framework-avkit==12.1
      - pyobjc-framework-avrouting==12.1
      - pyobjc-framework-backgroundassets==12.1
      - pyobjc-framework-browserenginekit==12.1
      - pyobjc-framework-businesschat==12.1
      - pyobjc-framework-calendarstore==12.1
      - pyobjc-framework-callkit==12.1
      - pyobjc-framework-carbon==12.1
      - pyobjc-framework-cfnetwork==12.1
      - pyobjc-framework-cinematic==12.1
      - pyobjc-framework-classkit==12.1
      - pyobjc-framework-cloudkit==12.1
      - pyobjc-framework-cocoa==12.1
      - pyobjc-framework-collaboration==12.1
      - pyobjc-framework-colorsync==12.1
      - pyobjc-framework-compositorservices==12.1
      - pyobjc-framework-contacts==12.1
      - pyobjc-framework-contactsui==12.1
      - pyobjc-framework-coreaudio==12.1
      - pyobjc-framework-coreaudiokit==12.1
      - pyobjc-framework-corebluetooth==12.1
      - pyobjc-framework-coredata==12.1
      - pyobjc-framework-corehaptics==12.1
      - pyobjc-framework-corelocation==12.1
      - pyobjc-framework-coremedia==12.1
      - pyobjc-framework-coremediaio==12.1
      - pyobjc-framework-coremidi==12.1
      - pyobjc-framework-coreml==12.1
      - pyobjc-framework-coremotion==12.1
      - pyobjc-framework-coreservices==12.1
      - pyobjc-framework-corespotlight==12.1
      - pyobjc-framework-coretext==12.1
      - pyobjc-framework-corewlan==12.1
      - pyobjc-framework-cryptotokenkit==12.1
      - pyobjc-framework-datadetection==12.1
      - pyobjc-framework-devicecheck==12.1
      - pyobjc-framework-devicediscoveryextension==12.1
      - pyobjc-framework-dictionaryservices==12.1
      - pyobjc-framework-discrecording==12.1
      - pyobjc-framework-discrecordingui==12.1
      - pyobjc-framework-diskarbitration==12.1
      - pyobjc-framework-dvdplayback==12.1
      - pyobjc-framework-eventkit==12.1
      - pyobjc-framework-exceptionhandling==12.1
      - pyobjc-framework-executionpolicy==12.1
      - pyobjc-framework-extensionkit==12.1
      - pyobjc-framework-externalaccessory==12.1
      - pyobjc-framework-fileprovider==12.1
      - pyobjc-framework-fileproviderui==12.1
      - pyobjc-framework-findersync==12.1
      - pyobjc-framework-fsevents==12.1
      - pyobjc-framework-fskit==12.1
      - pyobjc-framework-gamecenter==12.1
      - pyobjc-framework-gamecontroller==12.1
      - pyobjc-framework-gamekit==12.1
      - pyobjc-framework-gameplaykit==12.1
      - pyobjc-framework-gamesave==12.1
      - pyobjc-framework-healthkit==12.1
      - pyobjc-framework-imagecapturecore==12.1
      - pyobjc-framework-inputmethodkit==12.1
      - pyobjc-framework-installerplugins==12.1
      - pyobjc-framework-instantmessage==12.1
      - pyobjc-framework-intents==12.1
      - pyobjc-framework-intentsui==12.1
      - pyobjc-framework-iobluetooth==12.1
      - pyobjc-framework-iobluetoothui==12.1
      - pyobjc-framework-iosurface==12.1
      - pyobjc-framework-ituneslibrary==12.1
      - pyobjc-framework-kernelmanagement==12.1
      - pyobjc-framework-latentsemanticmapping==12.1
      - pyobjc-framework-launchservices==12.1
      - pyobjc-framework-libdispatch==12.1
      - pyobjc-framework-libxpc==12.1
      - pyobjc-framework-linkpresentation==12.1
      - pyobjc-framework-localauthentication==12.1
      - pyobjc-framework-localauthenticationembeddedui==12.1
      - pyobjc-framework-mailkit==12.1
      - pyobjc-framework-mapkit==12.1
      - pyobjc-framework-mediaaccessibility==12.1
      - pyobjc-framework-mediaextension==12.1
      - pyobjc-framework-medialibrary==12.1
      - pyobjc-framework-mediaplayer==12.1
      - pyobjc-framework-mediatoolbox==12.1
      - pyobjc-framework-metal==12.1
      - pyobjc-framework-metalfx==12.1
      - pyobjc-framework-metalkit==12.1
      - pyobjc-framework-metalperformanceshaders==12.1
      - pyobjc-framework-metalperformanceshadersgraph==12.1
      - pyobjc-framework-metrickit==12.1
      - pyobjc-framework-mlcompute==12.1
      - pyobjc-framework-modelio==12.1
      - pyobjc-framework-multipeerconnectivity==12.1
      - pyobjc-framework-naturallanguage==12.1
      - pyobjc-framework-netfs==12.1
      - pyobjc-framework-network==12.1
      - pyobjc-framework-networkextension==12.1
      - pyobjc-framework-notificationcenter==12.1
      - pyobjc-framework-opendirectory==12.1
      - pyobjc-framework-osakit==12.1
      - pyobjc-framework-oslog==12.1
      - pyobjc-framework-passkit==12.1
      - pyobjc-framework-pencilkit==12.1
      - pyobjc-framework-phase==12.1
      - pyobjc-framework-photos==12.1
      - pyobjc-framework-photosui==12.1
      - pyobjc-framework-preferencepanes==12.1
      - pyobjc-framework-pushkit==12.1
      - pyobjc-framework-quartz==12.1
      - pyobjc-framework-quicklookthumbnailing==12.1
      - pyobjc-framework-replaykit==12.1
      - pyobjc-framework-safariservices==12.1
      - pyobjc-framework-safetykit==12.1
      - pyobjc-framework-scenekit==12.1
      - pyobjc-framework-screencapturekit==12.1
      - pyobjc-framework-screensaver==12.1
      - pyobjc-framework-screentime==12.1
      - pyobjc-framework-scriptingbridge==12.1
      - pyobjc-framework-searchkit==12.1
      - pyobjc-framework-security==12.1
      - pyobjc-framework-securityfoundation==12.1
      - pyobjc-framework-securityinterface==12.1
      - pyobjc-framework-securityui==12.1
      - pyobjc-framework-sensitivecontentanalysis==12.1
      - pyobjc-framework-servicemanagement==12.1
      - pyobjc-framework-sharedwithyou==12.1
      - pyobjc-framework-sharedwithyoucore==12.1
      - pyobjc-framework-shazamkit==12.1
      - pyobjc-framework-social==12.1
      - pyobjc-framework-soundanalysis==12.1
      - pyobjc-framework-speech==12.1
      - pyobjc-framework-spritekit==12.1
      - pyobjc-framework-storekit==12.1
      - pyobjc-framework-symbols==12.1
      - pyobjc-framework-syncservices==12.1
      - pyobjc-framework-systemconfiguration==12.1
      - pyobjc-framework-systemextensions==12.1
      - pyobjc-framework-threadnetwork==12.1
      - pyobjc-framework-uniformtypeidentifiers==12.1
      - pyobjc-framework-usernotifications==12.1
      - pyobjc-framework-usernotificationsui==12.1
      - pyobjc-framework-videosubscriberaccount==12.1
      - pyobjc-framework-videotoolbox==12.1
      - pyobjc-framework-virtualization==12.1
      - pyobjc-framework-vision==12.1
      - pyobjc-framework-webkit==12.1
      - sausero==1.2.0
prefix: /Users/daniel/miniconda3/envs/yasone
