zeropoint = 29.093994518639892
filter = "Sloan_g"
zeropoint_err = 0.0223937905891854
airmass = 1.11968952945927
atm_ext = 0.1679534294188905
atm_ext_err = 0.0223937905891854
standard_star = "PG1528+062B"
standard_mag = 12.247
